---
collectors_default: all
ds_numsubordinate_records:
  - dc=example,dc=com

ldap_server_url: ldaps://389ds-bdb:3636
ldap_bind_dn: cn=directory manager
ldap_bind_pw: "12345678"
ldap_tls_skip_verify: true
