---
# Default set of collectors.
# Possible values:
# - `all`: enables all collectors by default.
# - `none`: disables all collectors by default.
# - `standard`: enables standard set of collectors.
#
# collectors_default: standard

# Enable specific collector.
# Specifying it together with `collectors_default: all` does not make sense, since all collectors are already enabled.
#
# collectors_enabled: []

# Database type.
# If the type is not specified, the exporter will attempt to detect it automatically.
# If the backend type is known in advance, it is best to specify it explicitly.
# This will avoid problems, for example, if the LDAP directory is unavailable when the exporter starts
# and the backend type cannot be detected automatically.
# Possible values:
# - `bdb`: Berkeley DB database backend.
# - `mdb`: LMDB database backend.
#
# ds_backend_type: mdb

# List of 389-ds backend databases.
# If no values ​​are specified, the exporter will attempt to find backends automatically.
# If the list is known in advance, it is best to specify it explicitly.
# This will avoid problems, for example, if the LDAP directory is unavailable when the exporter starts
# and the backend list cannot be detected automatically.
#
# ds_backend_dbs: []


# List of LDAP entries for which information about the number of subrecords (numsubordinates) will be collected.
#
# ds_numsubordinate_records: []

# The maximum duration the server will wait for a graceful shutdown of all resources when the application is stopping.
# During this period, the server stops accepting new connections, attempts to finish processing ongoing requests,
# and properly closes the HTTP server, LDAP connection pools, and other active resources.
# If the timeout is exceeded, any remaining open connections or resources will be forcibly closed to prevent the application from hanging.
# If the value is 0, it is assumed that the timeout has already expired and graceful shutdown will be skipped.
#
# shutdown_timeout: 5

# The address and port on which the server will listen for incoming connections.
# Use the format <host>:<port>. For example:
# ":9389" will listen on port 9389 on all network interfaces.
# "0.0.0.0:9389" will listen on port 9389 on all IPv4 interfaces.
# "192.168.0.10:9389" will listen on port 9389 only on 192.168.0.10.
#
# http_listen_address: "127.0.0.1:9389"

# HTTP endpoint where metrics are exposed.
#
# http_metrics_path: "/metrics"

# Maximum duration allowed for reading the entire request, including the body.
# A zero or negative value means no timeout.
#
# http_read_timeout: 10

# Maximum duration before timing out writes of the response.
# This timeout is reset whenever a new request’s header is read.
# A zero or negative value means no timeout.
#
# http_write_timeout: 15

# Maximum duration to wait for the next request when keep-alives are enabled.
# If zero, the value of ReadTimeout is used.
# If negative, or if both this and ReadTimeout are zero or negative, there is no timeout.
#
# http_idle_timeout: 60

# Maximum duration to wait for the client to send the beginning of the request after a connection is accepted.
# If the client doesn't send any data within this time, the connection will be closed.
# A value of 0 disables the timeout, meaning the server will wait indefinitely.
#
# http_initial_read_timeout: 3


# LDAP server URL in RFC-2255 format. For example:
# "ldap://localhost:389" or "ldaps://remote-server"
#
ldap_server_url: "ldap://localhost:389"

# DN of the account used to authenticate with the LDAP server.
#
ldap_bind_dn: "cn=directory manager"

# Password of the LDAP account.
#
# ldap_bind_pw: "12345678"

# Whether to perform a TLS check.
#
# ldap_tls_skip_verify: false

# Maximum size of the LDAP connection pool.
# Recommended and default value is 4. If set lower, metric collectors may block waiting for connections, slowing down the exporter.
# Values above 4 have no effect, as the current version of the exporter does not use more than 4 connections at once.
#
# ldap_pool_conn_limit: 5

# Timeout for the collector to receive a connection from the pool.
#
# ldap_pool_get_timeout: 5

# LDAP connection creation timeout.
# This time doesn't include the binding, only the connection opening.
#
# ldap_dial_timeout: 3

# The amount of time a connection can remain idle before it is closed.
#
# ldap_pool_idle_time: 10

# The lifetime of a connection after which it will be closed.
#
# ldap_pool_life_time: 5


# Logging level.
# Can be DEBUG, INFO, WARNING, or ERROR.
#
# log_level: INFO

# Log output target.
# Options:
# 'stdout' - logs are printed to standard output
# 'file'   - logs are written to a file
# 'both'   - logs are written to both stdout and a file
#
# log_handler: stdout

# Log file path.
# Only relevant if 'handler' is set to 'file' or 'both'.
# Make sure the system is configured to rotate this file (e.g., using logrotate).
#
# log_file: /var/log/389-ds-exporter/exporter.log

# STDOUT log format.
# Options: text, json
# The 'text' format is the default and is convenient for syslog.
# The 'json' format is useful for parsing logs or sending to external systems.
# Only applies if 'handler' is 'stdout' or 'both'.
#
# log_stdout_format: text

# File log format.
# Options: text, json
# Applies only if 'handler' is 'file' or 'both'.
#
# log_file_format: json
