---
# Default set of collectors.
# Possible values:
# - `all`: enables all collectors by default.
# - `none`: disables all collectors by default.
# - `standard`: enables standard set of collectors.
#
# collectors_default: standard

# Enable specific collector.
# Specifying it together with `collectors_default: all` does not make sense, since all collectors are already enabled.
#
# collectors_enabled: []

# Database type.
# If the type is not specified, the exporter will attempt to detect it automatically.
# If the backend type is known in advance, it is best to specify it explicitly.
# This will avoid problems, for example, if the LDAP directory is unavailable when the exporter starts
# and the backend type cannot be detected automatically.
# Possible values:
# - `bdb`: Berkeley DB database backend.
# - `mdb`: LMDB database backend.
#
# ds_backend_type: mdb

# List of 389-ds backend databases.
# If no values ​​are specified, the exporter will attempt to find backends automatically.
# If the list is known in advance, it is best to specify it explicitly.
# This will avoid problems, for example, if the LDAP directory is unavailable when the exporter starts
# and the backend list cannot be detected automatically.
#
# ds_backend_dbs: []

# List of LDAP entries for which information about the number of subrecords (numsubordinates) will be collected.
#
# ds_numsubordinate_records: []

# The maximum duration the server will wait for a graceful shutdown of all resources when the application is stopping.
# During this period, the server stops accepting new connections, attempts to finish processing ongoing requests,
# and properly closes the HTTP server, LDAP connection pools, and other active resources.
# If the timeout is exceeded, any remaining open connections or resources will be forcibly closed to prevent the application from hanging.
# If the value is 0, it is assumed that the timeout has already expired and graceful shutdown will be skipped.
#
# shutdown_timeout: 5

# LDAP server URL in RFC-2255 format. For example:
# "ldap://localhost:389" or "ldaps://remote-server"
#
ldap_server_url: "ldap://localhost:389"

# DN of the account used to authenticate with the LDAP server.
#
ldap_bind_dn: "cn=directory manager"

# Password of the LDAP account.
#
ldap_bind_pw: "12345678"

# Whether to perform a TLS check.
#
# ldap_tls_skip_verify: false

# Maximum size of the LDAP connection pool.
# Recommended and default value is 4. If set lower, metric collectors may block waiting for connections, slowing down the exporter.
# Values above 4 have no effect, as the current version of the exporter does not use more than 4 connections at once.
#
# ldap_pool_conn_limit: 5

# Timeout for the collector to receive a connection from the pool.
#
# ldap_pool_get_timeout: 5

# LDAP connection creation timeout.
# This time doesn't include the binding, only the connection opening.
#
# ldap_dial_timeout: 3

# The amount of time a connection can remain idle before it is closed.
#
# ldap_pool_idle_time: 10

# The lifetime of a connection after which it will be closed.
#
# ldap_pool_life_time: 5
