name: Testing and building of the exporter

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  GO_VERSION: 1.25.3

jobs:
  # Checking various aspects related to security - for example, vulnerability scanning
  Security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Download dependencies
        run: go mod download

      - name: Run linter
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: latest
          args: --timeout=5m

      - name: Run GoVulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: ${{ env.GO_VERSION }}
           go-package: ./...

      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@v2.22.10

      - name: Run Gosec Security Scanner
        run: gosec ./...

  Build:
    runs-on: ubuntu-latest
    needs: Security
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./... -race

      - name: Build binary
        run: make clean && make build

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: 389-ds-exporter
          path: build/389-ds-exporter
