---
name: Testing and building of the exporter
permissions:
  contents: read

on: # yamllint disable
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  GO_VERSION: 1.25.4
  GOSEC_VERSION: v2.22.10

jobs:
  # Checking various aspects related to lint and security
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Download dependencies
        run: go mod download

      - name: Install Semgrep
        run: |
          python3 -m pip install --upgrade pip
          pip install semgrep

      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@${{ env.GOSEC_VERSION }}

      - name: Run yamllint
        run: |
          set -e
          python3 -m pip install yamllint
          yamllint .

      - name: Run golangci linter
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: latest
          args: --timeout=5m

      - name: Run GoVulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: ${{ env.GO_VERSION }}
           go-package: ./...

      - name: Run Semgrep
        run: semgrep ci --config p/default --config p/golang --config p/gosec --exclude example

      - name: Run Gosec Security Scanner
        run: gosec ./...

  Build:
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./... -race

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build binary
        run: make clean && make build BRANCH=${{ steps.extract_branch.outputs.branch }}

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: 389-ds-exporter
          path: build/389-ds-exporter
